/*
 * SPDX-FileCopyrightText: Confluent Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright Confluent Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Adapted from the Confluent Schema Registry protobuf-serializer test fixtures
 * (https://github.com/confluentinc/schema-registry, protobuf-serializer/src/test/proto,
 * Apache License 2.0). The protobuf package and java_package were renamed for this
 * repository; the definitions are otherwise unchanged.
 */
syntax = "proto2";
package io.lakestream.ursa.kafka.serde.protobuf.test;

import "google/protobuf/descriptor.proto";

option java_package = "io.lakestream.ursa.kafka.serde.protobuf.test";

message FooBar {
  extensions 100 to 200;

  optional int32 foo = 1;
  optional string bar = 2;
  repeated FooBar nested = 3;

  message More {
    repeated int32 serial = 1;

    extend FooBar {
      optional string more_string = 150;
    }

    option (my_message_option).(More.more_string) = "foobar";
    option (my_message_option).(rep) = FOO;
    option (my_message_option).(rep) = BAR;
  }

  message More2 {
    repeated int32 serial = 1;

    extend FooBar {
      optional string more2_string = 151;
    }

    option (my_message_option) = {foo: 123, [FooBar.More2.more2_string]: "foobar", [rep]: []};
  }

  extend google.protobuf.EnumOptions {
    optional string foobar_string = 71001;
  }

  enum FooBarBazEnum {
    option (FooBar.foobar_string) = "foobar";

    FOO = 1;
    BAR = 2;
    BAZ = 3;
  }
}

extend google.protobuf.MessageOptions {
  optional FooBar my_message_option = 50099;
}

extend FooBar {
  optional FooBar.FooBarBazEnum ext = 101;
  repeated FooBar.FooBarBazEnum rep = 102;
}