/*
 * SPDX-FileCopyrightText: Confluent Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright Confluent Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Adapted from the Confluent Schema Registry protobuf-serializer test fixtures
 * (https://github.com/confluentinc/schema-registry, protobuf-serializer/src/test/proto,
 * Apache License 2.0). The protobuf package and java_package were renamed for this
 * repository; the definitions are otherwise unchanged.
 */
syntax = "proto3";

import "google/protobuf/timestamp.proto";

package io.lakestream.ursa.kafka.serde.protobuf.test;

option java_package = "io.lakestream.ursa.kafka.serde.protobuf.test";
option java_outer_classname = "NestedTestProto";
option java_multiple_files = false;

message UserId {
    oneof user_id {
        string kafka_user_id = 1;
        int32 other_user_id = 2;
        MessageId another_id = 3;
    }
}

message MessageId {
    string id = 1;
}

enum Status {
    ACTIVE = 0;
    INACTIVE = 1;
}

message ComplexType {
    oneof some_val {
        string one_id = 1;
        int32 other_id = 2;
    }
    bool is_active = 3;
}

/*
 * Complex message using nested protos and repeated fields
 */
message NestedMessage {
    UserId user_id = 1;
    bool is_active = 2;
    repeated string experiments_active = 3;
    google.protobuf.Timestamp updated_at = 4;
    Status status = 5;
    ComplexType complex_type = 6;
    map<string, string> map_type = 7;
    InnerMessage inner = 8;

    message InnerMessage {
        string id = 1 [json_name="id"];
        repeated int32 ids = 2 [packed=true];
    }

    enum InnerEnum {
        option allow_alias = true;
        ZERO = 0;
        ALSO_ZERO = 0;
    }

    reserved 14, 15, 9 to 11;
    reserved "foo", "bar";
}
