/*
 * SPDX-FileCopyrightText: Confluent Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright Confluent Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Adapted from the Confluent Schema Registry protobuf-serializer test fixtures
 * (https://github.com/confluentinc/schema-registry, protobuf-serializer/src/test/proto,
 * Apache License 2.0). The protobuf package and java_package were renamed for this
 * repository; the definitions are otherwise unchanged.
 */
syntax = "proto3";

package io.lakestream.ursa.kafka.serde.protobuf.test;

option java_package = "io.lakestream.ursa.kafka.serde.protobuf.test";
option java_outer_classname = "TestMessageProtos";

import "google/protobuf/descriptor.proto";

message TestMessage {
    string test_string = 1;
    bool test_bool = 2;
    bytes test_bytes = 3;
    double test_double = 4;
    float test_float = 5;
    fixed32 test_fixed32 = 6;
    fixed64 test_fixed64 = 7;
    int32 test_int32 = 8;
    int64 test_int64 = 9;
    sfixed32 test_sfixed32 = 10;
    sfixed64 test_sfixed64 = 11;
    sint32 test_sint32 = 12;
    sint64 test_sint64 = 13;
    uint32 test_uint32 = 14;
    uint64 test_uint64 = 15;
}

message TestMessage2 {
    string test_string = 1;
    bool test_bool = 2;
    bytes test_bytes = 3;
    double test_double = 4;
    float test_float = 5;
    fixed32 test_fixed32 = 6;
    fixed64 test_fixed64 = 7;
    int32 test_int32 = 8;
    int64 test_int64 = 9;
    sfixed32 test_sfixed32 = 10;
    sfixed64 test_sfixed64 = 11;
    sint32 test_sint32 = 12;
    sint64 test_sint64 = 13;
    uint32 test_uint32 = 14;
    uint64 test_uint64 = 15;
    TestMessage test_message = 16;
}
