{
  "type": "record",
  "name": "AllLogicalTypesRecord",
  "namespace": "io.lakestream.avro",
  "fields": [
    {
      "name": "uuidField",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "decimalField",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 10,
        "scale": 2
      }
    },
    {
      "name": "dateField",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "timeMillisField",
      "type": {
        "type": "int",
        "logicalType": "time-millis"
      }
    },
    {
      "name": "timeMicrosField",
      "type": {
        "type": "long",
        "logicalType": "time-micros"
      }
    },
    {
      "name": "timestampMillisField",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "timestampMicrosField",
      "type": {
        "type": "long",
        "logicalType": "timestamp-micros"
      }
    },
    {
      "name": "localTimestampMillisField",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    },
    {
      "name": "localTimestampMicrosField",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-micros"
      }
    }
  ]
}
