#
# SPDX-FileCopyrightText: 2026 OpenLakestream contributors <https://openlakestream.org>
# SPDX-License-Identifier: Apache-2.0
#

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} - %-5level - [%t]  %logger{36} - %msg%n

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT

appender.file.type = File
appender.file.name = FileAppenderForUrsaStorage
appender.file.fileName = ursa-storage-wal.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} - %-5level - [%t]  %logger{36} - %msg%n

logger.ursa.name = io.lakestream.ursa.storage.impl.ObjectWalStorageImpl
logger.ursa.level = info
logger.ursa.additivity = info
logger.ursa.appenderRefs = file
logger.ursa.appenderRef.file.ref = FileAppenderForUrsaStorage
