#
# SPDX-FileCopyrightText: 2026 OpenLakestream contributors <https://openlakestream.org>
# SPDX-License-Identifier: Apache-2.0
#

#


# The real storage type, available value is: [local, s3]
backendStorageType=local

# The backend storage path.
storagePath=data

# The wal storage type, available value is: [SIMPLE, COMPOSITE]
walStorageType=SIMPLE

# The id generator type for the wal log file. Available value is: [MEMORY, RANDOM, OXIA, UUID]
idGeneratorType=UUID

asyncCleanupWhenTrimmingData=false
