/*
 * SPDX-FileCopyrightText: 2026 OpenLakestream contributors <https://openlakestream.org>
 * SPDX-License-Identifier: Apache-2.0
 */
syntax = "proto3";

package io.lakestream.ursa.compact;

import "google/protobuf/descriptor.proto";

option java_package = "io.lakestream.ursa.compact";
option java_outer_classname = "TestProtoVariant";


message UserEventWithVariant {
  string id = 1;
  int64 age = 2;
  bool active = 3;
  double score = 4 [(logical_type) = "variant"];
  repeated string tags = 5 [(logical_type) = "variant"];
  map<string, string> attributes = 6 [(logical_type) = "variant"];
  Address address = 7 [(logical_type) = "variant"];
}

message Address {
  string street = 1;
  string city = 2;
}

// 1. Define the option data type (a string in this case)
extend google.protobuf.FieldOptions {
  // 2. Give the option a unique integer tag (1001 is a common starting point)
  string logical_type = 1001;
}